#pragma once

#define GEMSGUI_VERSION "3.12.0"
#define GEMSGUI_VERSION_HASH "9f5b3916"
#define GEMSGUI_GIT_BRANCH "master"
#define GEMSGUI_OSX "Darwin"
#define GEMSGUI_COMPILER_ID "AppleClang"
#define GEMSGUI_COMPILER_VERSION "21.0.0.21000334"
#define GEMSGUI_QT_VERSION "6.11.2"
