name: GEMSGUI

dependencies:
  - gxx_linux-64=9.4.0  # [linux]
  - cmake>=3.13
  - ninja # [unix]
  - make  # [win]
  - git
  - ccache  # [unix]
  - gems3k>=4.3.6
  - thermofun>=0.4.3
  - cppzmq
  - qt6-main=6.6.0
  - qt6-charts=6.6.0
  #- qt-main=5.15.8
  - mesa-libgl-devel-cos7-x86_64 # [unix]

environment:

  LD_LIBRARY_PATH:                                                   # [unix]
    - {{ root }}/artifacts/lib                                       # [unix]

  PATH:                                                              # [win]
    - {{ root }}\artifacts\bin                                       # [win]

