name: GEMSGUI

dependencies:
  - gxx_linux-64=9.4.0  # [linux]
  - cmake>=3.13
  - ninja # [unix]
  - make  # [win]
  - git
  - ccache  # [unix]
  - gems3k
  - nlohmann_json
  - spdlog=1.10.0
  - cppzmq
  - qt>=5.12.5
  - mesalib
  - mesa-libgl-cos6-x86_64
  - libselinux-cos6-x86_64
  - libxxf86vm-cos6-x86_64
  - xorg-libxext
  - xorg-libxau
  - xorg-libxdamage

environment:

  LD_LIBRARY_PATH:                                                   # [unix]
    - {{ root }}/artifacts/lib                                       # [unix]

  PATH:                                                              # [win]
    - {{ root }}\artifacts\bin                                       # [win]

